language: node_js
node_js:
- '0.10'
sudo: false
cache:
  directories:
  - node_modules
branches:
  only:
  - master
script:
- npm test
- npm run archive
deploy:
- provider: releases
  api_key:
    secure: RFbei/wvyWwwZp+bgnjE69bLxL7vNQ8Ui8izlh83a2sP8e6kKCcHo4dH/AqW2RseK+kVqSyvR6MmYnRF2b+T0z8R2xR+wAHevKagpv7xNS17hvwY1Y4ilza7NQ/B9pKK2V0A2mw2+D4djSpCDoYmFvsmoK00k7PswUihrPERVXYXL6KoW42LbgUomAD3E8CzlZgaYM5VkcTXhfNw9JCXQvKNFTK347ssjMIcwcjjkyEDdxDhuCfnWU3LFAvWxJk6ljxr0L3Vm8Fa85lAcFZKjkpH7VWg8H+XbwMBaQwATRT6xvtSrZBMRO+bRLVg2ECuLkB4qCmmdlY188bbJ4EB1iQaGqCRCp96IhSGZBq8yyUpuT6Aon91eOIrRT0DUe7ys8BXiBDzsB5Cy/DJVDfMSwhhAlbC9jySBelmF7d70Gtfmok3oAUqRwBrwCTc5onIHZ2i8+r+BB1cTG9Flsq12PjWRGCkYh2busZywZv5B9ygD/qpY0Z8z6L8u7eS0SHZJ9zwLlOxsqAqAeLr6M0uQEqVGP+KexQhNOI36tZkBEaTpLRwgRBL5/VGIpUt4YznA0bgcJFuqZeBDFSnO8kWe1kso1zujQxxCzOpN0FkxRf7ZBLDiVxR58yQXUYqxjwkx35PWORZNDmp3o5pTb/E7wYuhC1FIE4OvrCS8oxkYic=
  file: archive.zip
  skip_cleanup: true
  on:
    repo: chatwork/lambda-sns-to-chatwork-function
    branch: master
    tags: true
- provider: lambda
  access_key_id: ${AWS_SECRET_ACCESS_KEY}
  secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  function_name: lambda-sns-to-chatwork-function
  role: arn:aws:iam::218523217220:role/lambda-sns-to-chatwork-function-executer
  module_name: src/index
  handler_name: handler
  description: Notify the SNS to chatwork.
  timeout: 60
  memory_size: 128
  zip: archive.zip
  skip_cleanup: true
  on:
    repo: cw-ozaki/lambda-sns-to-chatwork-function
    branch: master
env:
  global:
  - CHATWORK_SEND_ROOM_ID=20702912
  - CHATWORK_MESSAGE_TEMPLATE='<%- Message %>'
  - secure: bhBdM4sfB5RgJcjxSlaJvmXt1Ov3qq8gE3M6zw5egAB/gKtSRZlhxcdRCMzbOyMTuu9UbSjAR2T3xRL5hzjUQjo49c1kWH26TPIbOwVG2aL9JQzAxJaaozfskSsDKOMIu15CZrKwjfMMId5xhKTZm3fyNapoMEdbDqe2WhDGoPFESvKUcL+u46ceJY8kAtejfbo1l4+TrU1Hx7yeOSnFOLGs3jPImlfSJ1UQ5ZJYz7PY+njrynT/Ux0yqfLehQGg3VT188ZdfGqlrqwyCcYXn5UUxLZn9otCehNTCwBu6kdDd5y9xYfT+TOfq6nOt9340aQP6KNLe3ou4nG5XcNJerGXkuMp6tYWNZwboZXFIu5DolQGrE6LOdobVOgk0GKWlyAk5qodS8p/M6B+kTSGoEpePGwkV5klWpHv8HZIBAf50q0HwrfzqBqv7xFytc0yLbFMAvt1lOxp/zu0TeoTPYySCy89VvcCummZin+BQ33J3LK75rE8RZVyhI4MVsMNswh5yid9GyJQjOAb3K3+0bw80M9v8e9dRgWyN3bYGnYthZzCace+exiM7gilB5s3WW8m0YN9Pp+xEA0vcsSJJoivKJqyPgrfuZOdcslSocaQ+UXNkz+uM99iVnz/QRtRV3BnArHRw2edeOkEgZf6zc1oDrJjeWfj+lL0UfiB89I=
  - secure: c9nUFS9JIB7Jk8NEibSBZvIUOH4PYNvzfucWiiemzD1JsJXP+2C7Vb+apJ6m8tlOncgt5DedpmjSP2lSK4dll6kNEOsFSErl/06JU7FxMxZ5F4uhu2TfQr1O44rL7B6xmlm3czVMidDusL9B2EIvwCvozyxGRbzJFhBoJ16n1h/lf0lg8Y0x4VUHKzDlydHqvqXkJvnk1unVeOnhDrAU7c81YpfvQAudOflUuxFTKkQWG3AYFZdrjBxGJPDLQiqWKFqINMWiujC0P8cCZPYLZyR3XvCCPlTUeu3Z+4cbTIludVfk4lNzMAQ3BEDiJGAlWiJfCh4OLQ/VN2YR483AQr0DjNi3O+U41urg6i9K6q60N7fHDfAiUGD3Z/Q1WRe5nVM4mXtZ8vaK3uq944+QGuaqbvowmErCj9rNCUx2HFreHnOhDuJuL9wleXqbbFCQkbZCnwWHlnHxH9xd6AuNg9BsL/xqmSn75iMaumY4iJnPC7x3Q3EjD9hXB709EHQJbeoypvTC0PzRHZtvYGnhByjaVt4NLDzjod8gXZtrLSvgVjJ3alwpQFOgTCNDguN4daQ1ZmXU5TCH6a9SNPsn3QSHXf8FutokQzI/KGHqQobFWvis1ibNNgVg2JUsQd4+4SRyG+9ZeQBoVh/f0jmm1EPGZbnJbx2p44/n9viNevI=
  - secure: co8E3TTPBK+wNOISdE6NIvIBdpbyOglTi4Yi7WFN6B2P6MIDK07NjBBW0Zetivh1xtgECW0mr+xmQTtMnB2hY7l+jBuA7KfJyrQilw8WY8vHaz/bTC7Ngrcr9qJER2a15DAtp4MrT8BgukmutAjwgYw3KWBK3SqjFhFN3I8u0EtPsGTD3CEa9v+rZecULvcLeBAPIO+i7j1BKF86gq3ZmlBvX3oDV3o4fampJ4xnVsn8EHJcIa4iSrOctlAZSvcCMRc2JGMSHrvPNDi5M+CFK9p+UsbP+V34qywNG2ChFlgzOvUPGE7T6wwXaVYgSmYHQo0n/1YBj7x2OPDJ8hNKnXrzhgVO6nSzUX1mqaJoHoxrF1NMYB1Sfi7PDP2y2qAP9ROODE22MJhBcdtnO8O6ZvIQpEK3+XtmavPyG9ZIBl7e2DmtL5BXl48C3SUH/FyWY90zqSTeeocphBtbHg8xqzHYnHEwFJHF7jhsvOnxB4lpI0Ft5/AAi9ZKcgZsXs2iAajM7d5b8JRRacphCordR6VuDIUG0NQQdUODyL6evigYWtcNDhfcfeQUcF0elOLnVv3nkl0EGU6ocW+1TJr4eoOYiXPJBX1XJmnvjTVJjdIenYIqsNRfn1eULQxXmFrNc+4ssRDt8iFTV/pW8crQziAUZZtsq9SyEth9zSbHicE=