language: node_js
node_js:
- '0.10'
sudo: false
cache:
  directories:
  - node_modules
branches:
  only:
  - master
script:
- npm test
- npm run archive
deploy:
- provider: releases
  api_key:
    secure: RFbei/wvyWwwZp+bgnjE69bLxL7vNQ8Ui8izlh83a2sP8e6kKCcHo4dH/AqW2RseK+kVqSyvR6MmYnRF2b+T0z8R2xR+wAHevKagpv7xNS17hvwY1Y4ilza7NQ/B9pKK2V0A2mw2+D4djSpCDoYmFvsmoK00k7PswUihrPERVXYXL6KoW42LbgUomAD3E8CzlZgaYM5VkcTXhfNw9JCXQvKNFTK347ssjMIcwcjjkyEDdxDhuCfnWU3LFAvWxJk6ljxr0L3Vm8Fa85lAcFZKjkpH7VWg8H+XbwMBaQwATRT6xvtSrZBMRO+bRLVg2ECuLkB4qCmmdlY188bbJ4EB1iQaGqCRCp96IhSGZBq8yyUpuT6Aon91eOIrRT0DUe7ys8BXiBDzsB5Cy/DJVDfMSwhhAlbC9jySBelmF7d70Gtfmok3oAUqRwBrwCTc5onIHZ2i8+r+BB1cTG9Flsq12PjWRGCkYh2busZywZv5B9ygD/qpY0Z8z6L8u7eS0SHZJ9zwLlOxsqAqAeLr6M0uQEqVGP+KexQhNOI36tZkBEaTpLRwgRBL5/VGIpUt4YznA0bgcJFuqZeBDFSnO8kWe1kso1zujQxxCzOpN0FkxRf7ZBLDiVxR58yQXUYqxjwkx35PWORZNDmp3o5pTb/E7wYuhC1FIE4OvrCS8oxkYic=
  file: archive.zip
  skip_cleanup: true
  on:
    repo: chatwork/lambda-sns-to-chatwork-function
    branch: master
    tags: true
- provider: lambda
  access_key_id: "${AWS_ACCESS_KEY}"
  secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
  function_name: lambda-sns-to-chatwork-function
  role: arn:aws:iam::218523217220:role/lambda-sns-to-chatwork-function-executer
  module_name: src/index
  handler_name: handler
  description: Notify the SNS to chatwork.
  timeout: 60
  memory_size: 128
  zip: archive.zip
  skip_cleanup: true
  on:
    repo: cw-ozaki/lambda-sns-to-chatwork-function
    branch: master
env:
  global:
  - secure: bhBdM4sfB5RgJcjxSlaJvmXt1Ov3qq8gE3M6zw5egAB/gKtSRZlhxcdRCMzbOyMTuu9UbSjAR2T3xRL5hzjUQjo49c1kWH26TPIbOwVG2aL9JQzAxJaaozfskSsDKOMIu15CZrKwjfMMId5xhKTZm3fyNapoMEdbDqe2WhDGoPFESvKUcL+u46ceJY8kAtejfbo1l4+TrU1Hx7yeOSnFOLGs3jPImlfSJ1UQ5ZJYz7PY+njrynT/Ux0yqfLehQGg3VT188ZdfGqlrqwyCcYXn5UUxLZn9otCehNTCwBu6kdDd5y9xYfT+TOfq6nOt9340aQP6KNLe3ou4nG5XcNJerGXkuMp6tYWNZwboZXFIu5DolQGrE6LOdobVOgk0GKWlyAk5qodS8p/M6B+kTSGoEpePGwkV5klWpHv8HZIBAf50q0HwrfzqBqv7xFytc0yLbFMAvt1lOxp/zu0TeoTPYySCy89VvcCummZin+BQ33J3LK75rE8RZVyhI4MVsMNswh5yid9GyJQjOAb3K3+0bw80M9v8e9dRgWyN3bYGnYthZzCace+exiM7gilB5s3WW8m0YN9Pp+xEA0vcsSJJoivKJqyPgrfuZOdcslSocaQ+UXNkz+uM99iVnz/QRtRV3BnArHRw2edeOkEgZf6zc1oDrJjeWfj+lL0UfiB89I=
  - CHATWORK_SEND_ROOM_ID=20702912
  - CHATWORK_MESSAGE_TEMPLATE='<%- Message %>'
  - secure: LeMZpGBuwzboBOce3rvaOCNTTHusgaHmYTrH2rOBDYSJN52/7eD9flmuXL783bYgg5R9Mv17M+AKu3eVXLovocwNbVc0zcTybTBURSYgbbDU35rkBywSLEc3H3lI3Ve3wrAtTYfK8eTZjYzMDrFW5fAtyhre/WJhP0XOCpFnYrUUWsdOz7YXBA77uob4av8GqojjQYO9eVoWS4CkyK81UpRydAQr/Sl01uG88ljQI5JzeMkkn9Jbq7q6c1s1OiPQk8lGQ2i1WbbJ4ZZe27RRB2QymvqYpezSFUD+Tp7NK/oJs0HlmDxSKWNC/aNiCLSCuaYiauNQVPzb0YOjz1clBpRGw5fffIhfnxjAQ7Xi5RFPg7JAltld3cajPgGGc4JEpJDLB0OOOMuF3Ts7SWhu/lacHVEQX40Qdus7ouzIVFNw2YPquTO3agJjuWqM4Gwj9bzISTGME7/IyDnAHjgJrTG2gUKY9ue0ORJWQXxOBZntBkyzVrR89BrRcfHTXVbOELMakzXtZLL1EjFQL8Bp/7ihgvIrTL1z/wvGvBeLWb1vEulGXrHOEgXehTwBL4oh94tIwbn4d3EpxHTJO9zFnoSBvkHT3I4bcX2zR0z9x6yfuzGZQUwFFlu1z4sL2vf/+STLCkE2JbAOdYs+wfbdKSBWuJvcae9JARIZwYimGbw=
  - secure: bC3IInZ/UOaMRqF8muLx9k0208+JyNUyUML3EnMXX6hEKZoCBtNJMeAy9paFH36G/G1kHSLMLEFGb2pRYfbfCrTL0sfFgof4R72qiV/haTdbdtbn79yemktrDcvu1fR1K9ICpASrmVQeLSNv+AZLhqgeu9u4yarJ8NhbWRV7FTOFlJ8oJu76kkrtPkHOXj0knfd+rT+g3O0nVq+yWTGHuMh2wttX4rfivs78ZGHR74q4HhdvVy/4gJ5g1YtGzuRqbjSJTlfCrTD8BblZ4QoAI/vrWF2TXDs0yi/6e7+WtuUvQG93HknDxMN+imjW1TZLACVgtlcgzAFbx+sHMLnaTVeSSbgJ5EXDcBKJ9MgBumzowqotJDFQ8kWRVbqZKpKmdTebLO7W+x5TnqQce5hGFB5qYF1bdVZcCt+0FVS5ls+SBJyi8iFJsWgTXj1BQdjhzwcWyaEVXMxEFJb3F3IQF5B7tKWjYsuRs8S33I61aIXEKpWG73tRIaGV8VDCJbdzQ5nUvzwE6QHaFE+pph3n1W4PIo4EaGPyoHeRovbOQ6BdpJKQVTQqUsvgfX7IvM73nLx3MGEpxbValG+ipB/oQjkHtCXNqtOViHuwoBrHaXKZkDfGR/oyxXaWpynRQIE/QItWmASX/mWl+a9ngMqfI7bbTadU4Z5ou1osaibg+Xw=
  - AWS_REGION=ap-northeast-1